import '../../../assets/globals.scss';
import styles from "@/app/(backend)/admin/(auth)/styles.module.scss";
import Image from "next/image";
import BgAuth from "@/assets/images/auth/back-ground-auth.png";

export const metadata = {
  title: 'Login | Base nextJS',
  description: 'Generated by create next app',
}

export default function RootLayoutAuth({ children }) {
  return (
    <html lang="en">
    <body>
      <div className={styles.layoutWrap}>
        <Image
          className={styles.imgWrap}
          src={BgAuth}
          alt="Picture of the author"
        />
        {children}
      </div>
    </body>
    </html>
  )
}
