import styles from './styles.module.scss';
import {Col, Row} from "antd";
import {getData} from "@/actions/home";

export const metadata = {
  title: 'Trang chủ | Base NextJs',
  description: 'Generated by create next app',
}

export default async function Home() {
  let employees = await getData();

  return (
    <div>
      <div className={styles.sectionProductWrap}>
        <Row gutter={10}>
          {
            employees.map((employee, index) => {
              return(
                <Col key={employee.id} span={6}>
                  <div className={styles.productWrap}>
                    {employee.name}
                  </div>
                </Col>
              )
            })
          }
        </Row>
      </div>
    </div>
  )
}
